### ISSUE TITLE
/oauth/token fails to load - It was not possible to parse your key

### ISSUE THREAD

**Issue by ochorocho** [fgtclb/typo3-oauth2-server#1]
I'm using this little app for testing:
https://github.com/lloy0076/simple-oauth2-client-example

I've created a config and configured the extension setting in TYPO3 (v9.5.20)  + created keys according to the readme.md.

When trying to authenticate it get the following error:

```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: It was not possible to parse your key, reason: error:0906D06C:PEM routines:PEM_read_bio:no start line | InvalidArgumentException thrown in file /var/www/vhosts/XXXX/deployment/production/releases/20200820134204/vendor/lcobucci/jwt/src/Signer/OpenSSL.php in line 90. Requested URL: https://www.DOMAIN.de/oauth/token
```

Any idea why the server can't parse the key?

Thank you :-)

**Comment by andreaswolf** [comment]
Can you check if your keys start with 
```-----BEGIN RSA PRIVATE KEY-----```
and
```-----BEGIN PUBLIC KEY-----```
respectively?

**Comment by ochorocho** [comment]
Yes, both keys are wrapped with `-----BEGIN RSA PRIVATE KEY-----` and `-----BEGIN PUBLIC KEY-----`

**Comment by mbrodala** [comment]
@ochorocho Can you ensure that only `LF` and not `CR+LF` is used as line endings in the key files?

**Comment by ochorocho** [comment]
`file` shows nothing, iirc it show only additional output if it `CR+LF`

```
-bash-4.2$ file private.key 
private.key: PEM RSA private key
-bash-4.2$ file public.key 
public.key: ASCII text
```

**Comment by ochorocho** [comment]
Got it working. I have configured the wrong keys. So `public.key` was set as private key and vice versa. 🤦 

Thank you for your support and sorry for the noise.
